baseURL = "https://blog.kentalog.com/"
publishDir = "docs"
relativeURLs = true
locale = "ja-JP"
title = "kentalog blog"

[params]
  description = "AI × Creative"

[markup.goldmark.renderer]
  hardWraps = true
